[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "3e81b95694a78ba66e147182fe3cbf7832581ce7"
os = "macos"

    [[pandoc.download]]
    sha256 = "ddd3c6d6f18916ee2105307eddd6586e2523056020c74d62e94946348333d064"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.1.9+0/pandoc.v3.1.9.aarch64-apple-darwin.tar.gz"
[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "54319d418e7a07b429a402f3e8ee2bfa6793ef8a"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "7f2cc9abeadf258bd200dc628bf170df4c983c995b6b9ff561e21710a2d40eb5"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.1.9+0/pandoc.v3.1.9.aarch64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "3ba575124382ea05a0e14234633da95c98609b6e"
os = "macos"

    [[pandoc.download]]
    sha256 = "a6b81aaa380e16eb8674ba427c4e46927c5a4de8c19cf0d53b57c3669588fa7f"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.1.9+0/pandoc.v3.1.9.x86_64-apple-darwin.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "309da498a6a7de2dc855f609e0f558be10554974"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "c4b74bc87e99193c53d5c522e93c686b023a476443dc078c8a4bc3c5eedae35e"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.1.9+0/pandoc.v3.1.9.x86_64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "7d0ca8141f148fabb6be34a0015d2c92c1ff3ea5"
os = "windows"

    [[pandoc.download]]
    sha256 = "807d09e8a5b87619e504b56741dcfee65006f3c4e8b0907ea97c5fe676deea65"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.1.9+0/pandoc.v3.1.9.x86_64-w64-mingw32.tar.gz"
