[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "fbe976809bdeebe53603d2ae9339fa4277689367"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "9e5ba316a995fed8f613c72d21d1b3946eb83906fb1927c3101f1f72f1939626"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+0/pandoc.v2.19.2.aarch64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "5ed35de7eea073e83886fbd4cc29c17fa5adbbe5"
os = "macos"

    [[pandoc.download]]
    sha256 = "d93c21730521dea2f2ff3a0e4e28711cf857adac5bbd3607cef8f636d495b3d2"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+0/pandoc.v2.19.2.x86_64-apple-darwin.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "5307f213c687ae2c8722412045bd953b591890fb"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "6810fd687ebef74db83f33e8f8ef6d3df624cdcc8cf0185a8fcec67bd3cf84fb"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+0/pandoc.v2.19.2.x86_64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "8bb185723f2dd6225f4810b950ef2211f5178426"
os = "windows"

    [[pandoc.download]]
    sha256 = "ff0d5b7c41301e8deeee78359bdd4c77f56d4c45f41e64bd63a29dcf5fd8441a"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+0/pandoc.v2.19.2.x86_64-w64-mingw32.tar.gz"
