[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "49d0f9bdc1eca92f23f6e6dc90238d3007ffdf9d"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "e817e1887a2930f90f2943293aed6ab1740c914c76e52ae9bcf5f960a520f96c"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+1/pandoc.v2.19.2.aarch64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "180662987e2537e4bf01c6a86efaa0b2a3829fd9"
os = "macos"

    [[pandoc.download]]
    sha256 = "b83d21cc54c8377304473c322060988792446a885cbca7f1c16af7441db93cca"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+1/pandoc.v2.19.2.x86_64-apple-darwin.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "2ccd6d6715f222a7aa55346e25d55b2c01da86e8"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "ae7f65a286ea1837d9a058b9be24889410161e90e1f3cefe987be3eaa993aba2"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+1/pandoc.v2.19.2.x86_64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "b663d80e7294e9e6acccdac6e36c1a80badb3755"
os = "windows"

    [[pandoc.download]]
    sha256 = "355a86a6a293c7e1de643e4e29ef0572e08964671c2bd8868b38ec47342c2590"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.19.2+1/pandoc.v2.19.2.x86_64-w64-mingw32.tar.gz"
