[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "5deae4ee7251eedc6ce311a11ca76c33accbc6a7"
os = "macos"

    [[pandoc.download]]
    sha256 = "1a4d204a2842f6a283f680c50c8bed03519e99d84fcb733f529e13eae2aff365"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.2.0+0/pandoc.v3.2.0.aarch64-apple-darwin.tar.gz"
[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "32f16920c1de3144f3296865c4a411bc7b2ce2ae"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "52f07aa60b50d3f2f59fcbfbc3e1a76e6b100b0dd0486cb94e85d573e003c858"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.2.0+0/pandoc.v3.2.0.aarch64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "8cbb61e564b8492a13511bac573e6ea69412992f"
os = "macos"

    [[pandoc.download]]
    sha256 = "346c3e9c3401e263ac590c265146a9264a04c87107d91c09f8b5c234f33bd865"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.2.0+0/pandoc.v3.2.0.x86_64-apple-darwin.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "e79d88f5255cfd9a5cf6129af0b50770d0b1ba0d"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "548be98508b48b1da8f92e0423d195f68959d7735152c33944278f8fd7015bdc"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.2.0+0/pandoc.v3.2.0.x86_64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "7defda3a207f12fe17c97af33519178a06a4ec32"
os = "windows"

    [[pandoc.download]]
    sha256 = "412a6d65341a798cfe8937573e606a4bba79cfdfd05ac5504f1b8f5497aedfa7"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.2.0+0/pandoc.v3.2.0.x86_64-w64-mingw32.tar.gz"
