[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "3ba64f7797965b0bd663b17dfdc3cbfec0583f04"
os = "macos"

    [[pandoc.download]]
    sha256 = "78d6a68b39a26f8152bbfb4822e0374307a9ab53336a24afd33a78ffaf04668c"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.0.1+0/pandoc.v3.0.1.aarch64-apple-darwin.tar.gz"
[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "35f2ffe9fdb106014492391b14b9aece43e0439b"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "dcc50f15ae3d3591a5bdc61709297c39808187ea3558cc0211e9550112b42f29"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.0.1+0/pandoc.v3.0.1.aarch64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "3ba64f7797965b0bd663b17dfdc3cbfec0583f04"
os = "macos"

    [[pandoc.download]]
    sha256 = "78d6a68b39a26f8152bbfb4822e0374307a9ab53336a24afd33a78ffaf04668c"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.0.1+0/pandoc.v3.0.1.x86_64-apple-darwin.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "44f7d5a80cabcee2b530111be39d36ceb2a29854"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "a9d1b0b2eadbcc8631927abee241105fe32028b3da74457e0ecaa13cac5ddc5d"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.0.1+0/pandoc.v3.0.1.x86_64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "6705e41b1407a54de534cf955e48dc3c541aa091"
os = "windows"

    [[pandoc.download]]
    sha256 = "07ec5342dffedf8477a7c1324ee6000e59e2b8eb4132cc32ea6fbf1dd1783c98"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v3.0.1+0/pandoc.v3.0.1.x86_64-w64-mingw32.tar.gz"
